Repository deislabs/hippo, pull requests merged in 2022-06, with the labels that each got.

#836 read bindle URL from connection string
  src/Infrastructure/Jobs/NomadJob.cs
Labels: bug, API

#838 check for null channel reference
  src/Application/EnvironmentVariables/Commands/UpdateChannelEnvironmentVariablesCommand.cs
Labels: enhancement, API

#841 drop generator-wasm
  .github/release-image/Dockerfile
Labels: chore

#842 hippo-cli 0.12
  .devcontainer/Dockerfile
Labels: bug

#843 remove unused imports
  src/Application/Apps/Commands/DeleteAppCommand.cs
  src/Application/Apps/Commands/UpdateAppCommand.cs
  src/Application/Apps/Queries/GetAppQuery.cs
  src/Application/Apps/Queries/GetAppsQuery.cs
  src/Application/Certificates/Commands/CreateCertificateCommand.cs
  src/Application/Certificates/Commands/DeleteCertificateCommand.cs
  src/Application/Certificates/Commands/UpdateCertificateCommand.cs
  src/Application/Channels/Commands/CreateChannelCommand.cs
  src/Application/Channels/Commands/DeleteChannelCommand.cs
  src/Application/Channels/Commands/UpdateChannelCommand.cs
  src/Application/Channels/EventHandlers/ChannelDeletedEventHandler.cs
  src/Application/Channels/Queries/ChannelExtensions.cs
  src/Application/Channels/Queries/GetChannelLogsQuery.cs
  src/Application/Common/Interfaces/IJobService.cs
  src/Application/EnvironmentVariables/Commands/CreateEnvironmentVariableCommand.cs
  src/Application/EnvironmentVariables/Commands/DeleteEnvironmentVariableCommand.cs
  src/Application/EnvironmentVariables/Commands/UpdateEnvironmentVariableCommand.cs
  src/Application/EnvironmentVariables/Commands/UpdateEnvironmentVariableDto.cs
  src/Application/Jobs/Job.cs
  src/Application/Revisions/Commands/CreateRevisionCommand.cs
  src/Application/Revisions/Commands/DeleteRevisionCommand.cs
  src/Application/Revisions/Commands/RegisterRevisionCommand.cs
  src/Infrastructure/DependencyInjection.cs
  src/Infrastructure/Jobs/NomadJob.cs
  src/Web/Api/ChannelController.cs
  src/Web/Api/StorageController.cs
Labels: chore

#858 nullable types are not required
  src/Application/Apps/Queries/AppDto.cs
  src/Application/Common/Interfaces/BindleService/RevisionComponent.cs
  src/Application/Common/Interfaces/BindleService/RevisionComponentTrigger.cs
  src/Application/Common/Interfaces/BindleService/RevisionSpinToml.cs
  src/Application/Common/Interfaces/BindleService/RevisionTrigger.cs
  src/Application/Revisions/Commands/UpdateRevisionDetailsCommand.cs
  src/Application/Revisions/Queries/RevisionComponentDto.cs
Labels: bug

#879 fix: get jobs that are valid GUIDs
  src/Infrastructure/Services/NomadJobService.cs
Labels: bug, API

#885 Bugix 884/fix background color tabs
  src/Web/ClientApp/src/app/components/application/settings/settings.component.html
  src/Web/ClientApp/src/app/components/channel/channel.component.html
  src/Web/ClientApp/src/app/components/channel/logs/logs.component.html
  src/Web/ClientApp/src/app/components/environment-variable/list/list.component.html
Labels: bug, UI

#883 Bugfix 882/fix overview component align
  src/Web/ClientApp/src/app/components/channel/overview/overview.component.html
Labels: bug, UI

#887 Feature 886/show message when no bindles
  src/Web/ClientApp/src/app/components/application/new/new.component.html
Labels: enhancement, UI

#892 Added loader for each tab
  src/Web/ClientApp/src/app/components/application/new/new.component.html
  src/Web/ClientApp/src/app/components/application/new/new.component.ts
  src/Web/ClientApp/src/app/components/application/settings/settings.component.ts
  src/Web/ClientApp/src/app/components/channel/logs/logs.component.html
  src/Web/ClientApp/src/app/components/channel/logs/logs.component.ts
  src/Web/ClientApp/src/app/components/channel/overview/overview.component.html
  src/Web/ClientApp/src/app/components/channel/overview/overview.component.ts
  src/Web/ClientApp/src/app/components/environment-variable/list/list.component.html
  src/Web/ClientApp/src/app/components/environment-variable/list/list.component.ts
Labels: enhancement, UI

#898 Updating tabs when channel is changed
  src/Web/ClientApp/src/app/components/channel/logs/logs.component.ts
  src/Web/ClientApp/src/app/components/channel/overview/overview.component.ts
  src/Web/ClientApp/src/app/components/environment-variable/list/list.component.ts
Labels: bug, UI

#952 Job status api is still called after leaving the app list page
  src/Web/ClientApp/src/app/components/application/list/list.component.ts
Labels: bug, UI

#959 Renamed IBindleService to IStorageService
  src/Application/Apps/Commands/CreateAppCommandValidator.cs
  src/Application/Common/Interfaces/BindleService/IStorageService.cs
  src/Application/Common/Interfaces/BindleService/RevisionComponent.cs
  src/Application/Common/Interfaces/BindleService/RevisionComponentTrigger.cs
  src/Application/Common/Interfaces/BindleService/RevisionDetails.cs
  src/Application/Common/Interfaces/BindleService/RevisionSpinToml.cs
  src/Application/Common/Interfaces/BindleService/RevisionTrigger.cs
  src/Application/Revisions/Commands/ImportRevisionsCommand.cs
  src/Application/Revisions/Commands/UpdateRevisionDetailsCommand.cs
  src/Application/Revisions/EventHandlers/UpdateRevisionDetails.cs
  src/Application/Storage/Queries/GetStoragesQuery.cs
  src/Infrastructure/DependencyInjection.cs
  src/Infrastructure/Services/BindleService.cs
  tests/Hippo.FunctionalTests/FakeBindleService.cs
  tests/Hippo.FunctionalTests/TestBase.cs
Labels: refactor, API

#957 Fixed issue with bindle heath check, added response status code
  src/Infrastructure/HealthChecks/BindleHealthCheck.cs
  src/Web/Extensions/HealthCheckExtensions.cs
  src/Web/Extensions/HealthInfo.cs
  src/Web/Program.cs
Labels: enhancement, API

#964 load custom js if present
  src/Web/ClientApp/src/index.html
Labels: enhancement, UI

#965 expandable menu
  src/Web/ClientApp/src/app/components/navbar/navbar.component.html
  src/Web/ClientApp/src/app/components/navbar/navbar.component.ts
Labels: enhancement, UI

#972 remove mx-4
  src/Web/ClientApp/src/app/app.component.html
Labels: bug, UI

#979 fix nullability warnings
  src/Application/Channels/Commands/PatchChannelCommand.cs
  src/Core/Models/Filter.cs
  src/Core/Models/Page.cs
  src/Core/Serialization/FieldConverter.cs
Labels: refactor, API

#981 use operators `is null` and `is not null`
  src/Application/Channels/Commands/PatchChannelCommand.cs
  src/Application/Channels/EventHandlers/ChannelCreatedEventHandler.cs
  src/Application/Channels/Queries/GetChannelQuery.cs
  src/Application/Common/Extensions/IgnoreNoMapExtensions.cs
  src/Application/JobStatuses/Queries/GetJobStatusesQuery.cs
  src/Application/Revisions/Commands/UpdateRevisionDetailsCommand.cs
  src/Core/Models/Extensions/FieldExtensions.cs
  src/Core/Models/Extensions/FilteringExtensions.cs
  src/Infrastructure/Data/Interceptors/AuditableEntitySaveChangesInterceptor.cs
  src/Infrastructure/Services/BindleService.cs
  src/Infrastructure/Services/NomadJobService.cs
Labels: refactor
